### ISSUE TITLE
New Feature Request : Visible signature

### ISSUE THREAD

**Issue by pedropuppim** [JSignPdf/jsignpdf-php#10]
### Visible signature

![image info](https://i.imgur.com/ZKIzsF9.png)

**Comment by jeidison** [comment]
Fala @pedropuppim, beleza?

Para adicionar a "Visible signature" você precisa passar alguns parâmetros.

Exemplo:

```
$param = JSignParam::instance();
...
$params->setJSignParameters("-a -kst PKCS12 -V --bg-path PATH_COMPLETA_DA_SUA_IMG");

$jSignPdf   = new JSignPDF($param);
$fileSigned = $jSignPdf->sign();

```
Para remover o texto padrão que a lib adiciona junto com sua imagem, você precisa passar uma nova flag:

Exemplo:
```
$param = JSignParam::instance();
...
$params->setJSignParameters("-a -kst PKCS12 -V --bg-path PATH_COMPLETA_DA_SUA_IMG -l2-text ''");

$jSignPdf   = new JSignPDF($param);
$fileSigned = $jSignPdf->sign();

```
Nesse caso flag **-l2-text ''** fará com que o texto default fique em branco.

Você também pode mudar o posicionamento da imagem usando as seguintes flags:

-llx -lly 
(X,Y) Posição das assinaturas do canto esquerdo inferior da página

-urx -ury : 
(X,Y) Posição do canto superior direito da página

Valeu

**Comment by pedropuppim** [comment]
Maravilha @jeidison ! 
Muito obrigado e parabéns pela biblioteca.
